# Generated by Django 5.2.5 on 2025-08-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Planos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plano",
            name="bordes_externos",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="plano",
            name="imagen_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plano",
            name="sublotes",
            field=models.JSONField(default=list),
        ),
    ]
