# Generated by Django 5.2.5 on 2025-08-13 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Planos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Vendido', 'Vendido')], max_length=20)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Planos.plano')),
            ],
        ),
    ]
