# Generated by Django 5.2.5 on 2025-08-14 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lotes', '0001_initial'),
        ('Planos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['-creado'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AddField(
            model_name='lote',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='vertices',
            field=models.JSONField(default=list, help_text='Coordenadas de los vértices del lote'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='lote',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Planos.plano'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
