# Generated by Django 5.2.5 on 2025-08-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lotes", "0002_alter_lote_options_lote_actualizado_lote_creado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lote",
            name="medidas_lados",
            field=models.TextField(
                blank=True, help_text="Medidas de los lados del lote", null=True
            ),
        ),
    ]
